<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><?= T('登录') ?></h4>
      </div>
      <div class="modal-body">
        <?= V('form/error', ['form' => $form]) ?>
        <form id="login" role="form" method="post" action="login">
          <div class="form-group" style="margin-bottom: 12px;">
            <label for="exampleInputEmail1"><?= T('账号') ?></label>
            <input name="name" type="text" class="form-control" placeholder="<?= T('请输入账号') ?>">
          </div>
          <div class="form-group" style="margin-bottom: 12px;">
            <label for="exampleInputPassword1"><?= T('密码') ?></label>
            <input name="password" type="password" class="form-control" placeholder="<?= T('请输入密码') ?>">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <a type="button" href="" class="btn btn-default"><?= T('返回') ?></a>
        <button type="submit" form="login" class="btn btn-primary"><?= T('提交') ?></button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script>
require(['main'], function ($) {
  $('.modal').modal('show')
})
</script>