<div class="container">
  <h2 style="margin-bottom: 20px;">
    <small><?= H(\Gini\Config::get('site.short'))?></small>
    <br />
    <?= T('人员管理') ?>
  </h2>
  <div class="row">
    <div class="col-md-3">
      <form role="search" method="post">
        <div class="form-group has-feedback">
            <input type="text" class="form-control" name="keyword" placeholder="<?= T('查询用户') ?>">
            <span class="glyphicon glyphicon-search form-control-feedback" 
            aria-hidden="true" style="color: #AAA"></span>
        </div>
      </form>
    </div>
    <div class="col-md-9">
      <div class="btn-group pull-right">
        <a href="gini-ajax:ajax/user/add" class="btn btn-default">
          <i class="fa fa-plus" aria-hidden="true"></i>
        </a>
      </div>
    </div>
  </div>
  <?= V('message') ?>
  <table class="table table-hover">
    <thead>
      <th>#</th>
      <th><?= T('姓名') ?></th>
      <th><?= T('添加时间') ?></th>
      <th><?= T('操作') ?></th>
    </thead>
    <tbody>
      <?php
      if ($users) foreach ($users as $index => $user) :
      ?>
      <tr>
        <td><?= H($index) ?></td>
        <td><?= H($user->nickname) ?></td>
        <td><?= H($user->ctime) ?></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-warning btn-md">
              <a href="gini-ajax:ajax/user/edit/<?= $user->id?>" style="color:#FFF" >
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
            </button>
            <button type="button" class="btn btn-danger btn-md">
              <a href="gini-ajax:ajax/user/delete/<?= $user->id?>" style="color:#FFF" >
                <i class="fa fa-times" aria-hidden="true"></i>
              </a>
            </button>
          </div>
        </td>
      </tr>
      <?php
      endforeach;
      ?>
    </tbody>
  </table>
</div>