<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><?= T('编辑用户') ?></h4>
      </div>
      <div class="modal-body">
        <?= V('form/error', ['form' => $form]) ?>
        <form id="userEdit" class="form-horizontal" role="form" action="gini-ajax:ajax/user/edit/<?= H($user->id)?>">
          <div class="form-group">
            <label class="col-sm-2 control-label"><?= T('姓名') ?></label>
            <div class="col-sm-10">
              <input name="nickname" type="text" class="form-control" placeholder="<?= T('请输入姓名') ?>" value="<?= H($user->nickname)?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label"><?= T('账号') ?></label>
            <div class="col-sm-10">
              <input name="name" type="text" class="form-control" placeholder="<?= T('请输入账号') ?>" value="<?= H($user->name)?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label"><?= T('密码') ?></label>
            <div class="col-sm-10">
              <input name="password" type="password" class="form-control" placeholder="<?= T('请输入密码') ?>">
            </div>
          </div>
          <div class="form-group">
            <label class="col-sm-2 control-label"><?= T('确认密码') ?></label>
            <div class="col-sm-10">
              <input name="confirm" type="password" class="form-control" placeholder="<?= T('请再次输入密码') ?>">
            </div>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= T('关闭') ?></button>
        <button type="submit" class="btn btn-success" form="userEdit"><?= T('保存') ?></button>
      </div>
    </div>
  </div>
</div>

<script data-ajax>
require(['main'], function ($) {
  if ($('.modal').length > 0) {
    $(".modal:not(':eq(0)')").remove()
  }
  $('.modal').modal('show')

  form = $('form#userEdit')
  form.on('ajax-before', function (e) {
    $('.modal').remove()
  })

  $('.modal').on('hidden.bs.modal', function (e) {
    $('.modal').remove()
  })
})
</script>