<div class="container">
  <h2 style="margin-bottom: 20px;">
    <small><?= H(\Gini\Config::get('site.short'))?></small>
    <br />
    <?= T('文章管理') ?>
  </h2>
  <div class="row">
    <div class="col-md-3">
      <form role="search" method="post">
        <div class="form-group has-feedback">
            <input type="text" class="form-control" name="keyword" placeholder="<?= T('查询文章') ?>">
            <span class="glyphicon glyphicon-search form-control-feedback" 
            aria-hidden="true" style="color: #AAA"></span>
        </div>
      </form>
    </div>
    <div class="col-md-9">
      <div class="btn-group pull-right">
        <a href="admin/article" class="btn btn-default">
          <?= T('全部') ?>
        </a>
        <?php foreach (\Gini\ORM\Article::$TYPE as $key => $type) :?>
          <a href="admin/article/<?= H($key) ?>" class="btn btn-default">
            <?= T($type) ?>
          </a>
        <?php endforeach;?>
        <a href="gini-ajax:ajax/article/add" class="btn btn-default" style="height: 34px;">
          <i class="fa fa-plus" aria-hidden="true" style="line-height: 24px;"></i>
        </a>
      </div>
    </div>
  </div>
  <?= V('message') ?>
  <table class="table table-hover">
    <thead>
      <th>#</th>
      <th><?= T('标题') ?></th>
      <th><?= T('类型') ?></th>
      <th><?= T('发布时间') ?></th>
      <th><?= T('操作') ?></th>
    </thead>
    <tbody>
      <?php
      if ($articles) foreach ($articles as $index => $article) :
      ?>
      <tr>
        <td><?= H($index) ?></td>
        <td><?= H($article->title) ?></td>
        <td><?= T(\Gini\ORM\Article::$TYPE[$article->type]) ?></td>
        <td><?= H($article->ctime) ?></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-warning ">
              <a href="gini-ajax:ajax/article/edit/<?= $article->id?>" style="color:#FFF">
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
              </a>
            </button>
            <button type="button" class="btn btn-danger ">
              <a href="gini-ajax:ajax/article/delete/<?= $article->id?>" style="color:#FFF" >
                <i class="fa fa-times" aria-hidden="true"></i>
              </a>
            </button>
          </div>
        </td>
      </tr>
      <?php
      endforeach;
      ?>
    </tbody>
  </table>
</div>