<div class="container public-list" style="min-height: 768px;padding: 0px 15px 0px 44px;">
  <ol class="breadcrumb" style="margin-bottom: 7px;">
    <li><a href="article/list/<?= $type?>"><?= T(\Gini\ORM\Article::$PAGE_TYPE[$type]);?></a></li>
    <li class="active"><?= T('详情');?></li>
  </ol>
    <div class="container">
        <h3 style="text-align:center;line-height:50px"><?= H($articles->title);?></h3>
        <p><?= $articles->content;?></p>
    </div>
</div>