<div class="container public-list">
  <div class="col-md-12 article-right">
    <ol class="breadcrumb" style="margin-bottom: 7px;">
      <li><a href="article/list/<?= $type?>"><?= T(\Gini\ORM\Article::$TYPE[$type]);?></a></li>
    </ol>
    <?php foreach($articles as $article) :?>
      <div class="media">
        <div class="media-left" style="padding-right:25px">
          <div class="article-date">
            <h2 class="text-center"><?= H(date('d', strtotime($article->ctime)));?></h2>
            <div class="text-center"><?= H(date('Y.m', strtotime($article->ctime)));?></div>
          </div>
        </div>
        <div class="media-body">
          <a href="article/content/<?= $article->id?>" style="color:#a1a1a1;text-decoration: none;">
            <h4 class="media-heading" style="margin-bottom:17px"><?= H($article->title);?></h4>
            <?= mb_substr(strip_tags($article->content), 0, 100) ?>
          </a>
        </div>
      </div>
    <?php endforeach;?>
  </div>
</div>
