<div class="container" id="article" style="margin-top: 38px; margin-bottom: 38px;">
  <h3 class="homepage-title" style="margin-top: 0px; margin-bottom: 25px;">
    <a class="article-type active" type="<?= \Gini\ORM\Article::TYPE_NOTIC?>" style="text-decoration: none;"><?= T(\Gini\ORM\Article::$TYPE[\Gini\ORM\Article::TYPE_NOTIC]) ?></a>
    <div style="display: inline-block; width: 1px; background-color: #ddd;height: 20px;top: 3px;position: relative;margin: 0 10px;"></div>
    <a class="article-type" type="<?= \Gini\ORM\Article::TYPE_GUIDE?>" style="text-decoration: none;"><?= T(\Gini\ORM\Article::$TYPE[\Gini\ORM\Article::TYPE_GUIDE]) ?></a>
    <small class="pull-right">
      <a id="article-more" href="article/list/<?= \Gini\ORM\Article::TYPE_NOTIC?>"><?= T('更多>>') ?></a>
    </small>
  </h3>
</div>
<script>
require(['main'], function ($) {
  function ajaxArticle(type) {
    $.post('ajax/article/index/' + type, function (e) {
      $('a#article-more').attr('href', 'article/list/' + type);
      $('div.article-content').remove()
      $('#article').append(e)
    })
  }
  $('.article-type').click(function(){
    $('.article-type').removeClass('active')
    $(this).addClass('active')
    ajaxArticle($(this).attr('type'))
  })
  ajaxArticle("<?= \Gini\ORM\Article::TYPE_NOTIC?>")
})
</script>