<div class="container-fluid container-home-header">
	<div class="container">
	  <img src="assets/img/logo.png" style="z-index: 1;position: absolute;top: 17px;">
	  <!-- <img src="assets/img/logopic.png" style="z-index: 1;float: right;"> -->
	</div>
</div>
<div style="z-index: 1;position: fixed;right: 0px;bottom: 200px;">
	<h5 style="margin: 0;text-align: center;font-size: 17px;background-color: #FFF;"><?= H(T('请扫码预约！'))?></h5>
	<img src="assets/img/qrcod.jpg" style="width: 120px;">
</div>
<?= V('home/nav', ['route' => $route]) ?>
<?= $content ?>
<?= V('links', ['links' => $links]);?>
