<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0px; background-color: #313131;height:74px">
  <div class="container container-home-footer">
    <p class="text-center" style="margin-top:14px;color:#737373;font-size:13px"><?= T("Copyright2016 " . \Gini\Config::get('site.title') . ".All Rights Reserved") ?></p>
	<p class="text-center" style="color:#737373;font-size:13px"><?= T('基理科技 运维支持') ?>
    <a href="admin" style="text-decoration: none;">管理后台</a>
    </p>
  </div>
</nav>
