<title><?= H(\Gini\Config::get('site.title')) ?></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
<meta http-equiv = "X-UA-Compatible" content = "IE=edge,chrome=1" />
<meta name="renderer" content="webkit">
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<base href="<?= H(URL('/')) ?>">
<link href="assets/icon/favicon.png" rel="shortcut icon">
<link href="assets/css/bootstrap.css" rel="stylesheet">
<link href="assets/css/font-awesome.css" rel="stylesheet">
<link href="assets/css/home.css" rel="stylesheet">
<script data-main="assets/js/main.js" src="assets/js/require.js"></script>
