<title><?= H(\Gini\Config::get('site.title')) ?></title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
<!--允许浏览器搜录-->
<meta name="robots" content="index, follow" />
<meta name="description" content="仪器共享平台、仪器共享、仪器共享管理平台、大型仪器共享管理平台、大型设备共享平台、大型仪器共享、大型设备管理系统、实验器材管理系统、实验室设备与仪器管理系统、仪器仪表管理系统、实验室设备预约系统、实验室器材管理系统、实验室仪器管理软件、高校贵重仪器管理系统、实验仪器设备管理系统、实验室设备管理系统、精密仪器管理系统、学校仪器预约系统、仪器借还管理系统、实验室设备管理软件、实验室仪器管理系统、大型科学仪器共享系统、大型科学仪器共享管理系统、实验仪器共享管理系统、LIMS-CF、设备预约管理系统、高校设备管理系统、大型设备管理软件、大型仪器设备管理系统、大型仪器设备共享管理系统、实验仪器管理、仪器管理系统、仪器管理软件、仪器预约系统、仪器设备使用管理、仪器设备管理系统、学校仪器设备管理系统、仪器设备管理、大型仪器管理系统、实验仪器管理系统、仪器设备管理软件、仪器设备管理程序、仪器管理、学校仪器设备管理、高校仪器设备管理系统、设备仪器管理系统、大型仪器设备管理、实验室仪器预约系统、实验室仪器设备管理系统、大型仪器设备管理办法、实验室仪器管理、仪器室管理软件、试验仪器管理、大型仪器管理、医学实验室仪器设备管理、高校仪器共享平台、仪器共享网、实验室仪器共享、仪器设备共享、大型仪器设备共享、大型科学仪器共享平台、仪器共享管理系统、仪器设备共享平台、大型科学仪器共享、大型仪器设备开放共享、大型仪器设备共享平台、大型仪器共享管理、大型仪器设施共享系统、大型仪器共享系统、大型仪器服务共享平台、大型仪器共享平台、大型仪器共享管理系统" />
<meta http-equiv = "X-UA-Compatible" content = "IE=edge,chrome=1" />
<meta name="renderer" content="webkit">
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<base href="<?= H(URL('/')) ?>">
<link href="assets/icon/favicon.png" rel="shortcut icon">
<link href="assets/css/bootstrap.css" rel="stylesheet">
<link href="assets/css/font-awesome.css" rel="stylesheet">
<link href="assets/css/home.css" rel="stylesheet">
<script data-main="assets/js/main.js" src="assets/js/require.js"></script>
