<div class="login-div">
	<h4 style="background-color: #e3eef4;margin: 0;height: 46px;line-height: 46px;">
		<img src="assets/img/user.png" style="padding: 0 17px;"><?= H(T('用户登录'))?>
	</h4>
	<a href="<?= \Gini\Config::get('server.caslogin')?>" style="text-decoration: none;">
		<h4 style="
			width: 200px;
		    height: 50px;
		    margin: 50px auto;
		    text-align: center;
		    line-height: 50px;
		    background-color: #19a5eb;
		    border-radius: 10px;
		    color: #FFF;
		    font-size: 18px;">
			<?= H(T('本校师生登录'))?>
			<img src="assets/img/leftarrow.png" style="top: -2px;position: relative;left: 10px;">
		</h4>
	</a>
	<div style="height: 1px;background-color: #CCCCCC;width: 90%;margin: 0 auto;"></div>
	<a href="<?= \Gini\Config::get('server.login')?>" style="text-decoration: none;">
		<h4 style="
			width: 200px;
		    height: 50px;
		    margin: 50px auto;
		    text-align: center;
		    line-height: 50px;
		    background-color: #19a5eb;
		    border-radius: 10px;
		    color: #FFF;
		    font-size: 18px;">
			<?= H(T('校外用户登录'))?>
			<img src="assets/img/leftarrow.png" style="top: -2px;position: relative;left: 10px;">
		</h4>
	</a>
	<div style="height: 1px;width: 75%;margin: 0 auto;">
		<a href="<?= \Gini\Config::get('server.signup')?>" class="a-login" ><?= T('注册用户') ?></a>
		<a href="<?= \Gini\Config::get('server.recovery')?>" class="a-login" style="right: 35px;" ><?= T('忘记密码') ?></a>
	</div>
</div>