<?php
    $_setActive = function($selected) use($route) {
      return $route == $selected ? 'active' : '';
    };
?>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        
        <li class="<?= $_setActive('index')?>"><a href=""><?= T('首页') ?></a></li>
        <li class="<?= $_setActive('member')?>"><a href="member/list"><?= T('平台介绍') ?></a></li>
        <li class="<?= $_setActive('equipment')?>"><a href="equipment/list"><?= T('仪器列表') ?></a></li>
        <li class="<?= $_setActive('')?>"><a href=""><?= T('培训交流') ?></a></li>
        <li class="<?= $_setActive('article')?>"><a href="article/list"><?= T('通知公告') ?></a></li>
        <li class="<?= $_setActive('datum')?>"><a href="datum/list"><?= T('服务流程') ?></a></li>
        <li class="<?= $_setActive('rule')?>"><a href="rule/list"><?= T('规章制度') ?></a></li>
        <li class="<?= $_setActive('question')?>"><a href="question/list"><?= T('问题解答') ?></a></li>
        <li class="<?= $_setActive('')?>"><a href=""><?= T('联系我们') ?></a></li>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>