<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><?= T('添加附件') ?></h4>
      </div>
      <div class="modal-body">
        <?= V('form/error', ['form' => $form]) ?>
        <form id="downloadAdd" role="form" method="post" action="admin/download/add" enctype="multipart/form-data">
          <div class="form-group">
            <label class="control-label"><?= T('名称') ?></label>
            <input name="title" type="text" class="form-control" placeholder="<?= T('请输入名称') ?>">
          </div>
          <div class="form-group">
            <label class="control-label" for="file">
              <?= H(T('请选择要上传的附件')) ?>
            </label>
            <input id="file" type="file" name="file">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= T('关闭') ?></button>
        <button type="submit" class="btn btn-success" form="downloadAdd"><?= T('保存') ?></button>
      </div>
    </div>
  </div>
</div>

<script data-ajax>
require(['main', 'fileinput', 'assets/js/locales/zh.js', 'css!../css/fileinput'], function ($) {
  if ($('.modal').length > 0) {
    $(".modal:not(':eq(0)')").remove()
  }
  $('.modal').modal('show')

  $('.modal').on('hidden.bs.modal', function (e) {
    $('.modal').remove()
  })

  $("#file").fileinput({
    language: 'zh',
    showUpload: false,
    allowedFileTypes: ['html', 'text', 'video', 'audio', 'flash']
  })
})
</script>