<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><?= T('删除友情链接') ?></h4>
      </div>
      <div class="modal-body">
        <?= V('form/error', ['form' => $form]) ?>
        <form id="linkDelete" class="form-horizontal" role="form" action="gini-ajax:ajax/link/delete/<?= H($link->id)?>">
          <div class="form-group">
            <label class="col-sm-12"><?= T('确定要删除此友情链接吗？') ?></label>
            <input hidden="hidden" name="a" value="1">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><?= T('取消') ?></button>
        <button type="submit" class="btn btn-success" form="linkDelete"><?= T('确定') ?></button>
      </div>
    </div>
  </div>
</div>

<script data-ajax>
require(['main'], function ($) {
  if ($('.modal').length > 0) {
    $(".modal:not(':eq(0)')").remove()
  }
  $('.modal').modal('show')

  form = $('form#linkDelete')
  form.on('ajax-before', function (e) {
    $('.modal').remove()
  })

  $('.modal').on('hidden.bs.modal', function (e) {
    $('.modal').remove()
  })
})
</script>